- hosts: target
  vars_prompt:
  - name: dvd_dir
    prompt: "Enter dvd mount point: "
    private: no
  tasks:
  - file: 
     state: directory
     path: "/{{dvd_dir}}"

  - mount:
     src: "/dev/cdrom"
     path: "/{{dvd_dir}}"
     fstype: "iso9660"
     state: mounted

  - yum_repository:
     baseurl: "/{{dvd_dir}}/AppStream"
     gpgcheck: 0
     name: "AppStream_dvd"
     description: "AppStream repo"

  - yum_repository:
     baseurl: "/{{dvd_dir}}/BaseOS"
     gpgcheck: 0
     name: "Base_dvd"
     description: "BaseOS repo"


